name: kunkun
on:
  workflow_dispatch:
  schedule:
    - cron: '3 * * * *'
jobs:
  build:
    runs-on: macos-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/likoo-wool/Test.git ~/Test              
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/Test
          npm install
          npm install cron
          npm install request
          curl ipinfo.io/json
      - name: '【kunkun】'
        run: |
          cd ~/Test 
          node kunkun1.js  
